version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: emmart-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: emmart-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  web:
    build:
      context: ./web-app
    container_name: emmart-web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./web-app/.env
    depends_on:
      - backend

  admin:
    build:
      context: ./admin-panel
    container_name: emmart-admin
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./admin-panel/.env
    depends_on:
      - backend

volumes:
  mongo_data:
